name: "Check for version update in PR to Master"

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
    - master

jobs:
  master-pr-check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if version changed
      run: |
        version_changed=`git diff HEAD..origin/master package.json | grep version | wc -l | tr -d '[:space:]'`
        if [ $version_changed -gt 1 ]; then
          echo "Version has been modified; good to go!"
          exit 0
        else
          echo "Version has not been modified; failing..."
          exit 1
        fi
